### ISSUE TITLE
Minor issue: File permissions

### ISSUE THREAD

**Issue by kjcole** [paopre/Spontini#12]
The permissions on the executable are read and write but not execute, whereas the permissions on several readable files (images, Markdown files) includes executable. On my Linux box I fixed them with:

```
$ for i in $(find . -name "*.md");   do chmod 644 $i; done
$ for i in $(find . -name "*.jpeg"); do chmod 644 $i; done
$ for i in $(find . -name "*.png");  do chmod 644 $i; done
$ for i in $(find . -name "*.svg");  do chmod 644 $i; done
$ for i in $(find . -name "*.gif");  do chmod 644 $i; done
$ for i in $(find . -name "*.vlt");  do chmod 644 $i; done
$ chmod 755 SpontiniServer.py
```

**Comment by paopre** [comment]
This would add a sort of "install" script file for Linux which would be meaningless because the editor is not meant to be installed.

**Comment by kjcole** [comment]
It was more intended to illustrate what I did, as it also wouldn't be the solution for Windows users. I was thinking that it might be something you'd do on your end before pushing new commits to GitHub... A git commit or push hook "final check" or something. (Then again, it's a minor issue.)

**Comment by paopre** [comment]
On Win/Mac you already have a launcher for the editor, then you don't need anything else.
On Linux it's on your choice to launch the editor through the python command or by making the script executable.
