### ISSUE TITLE
Feature request: pipenv as an alternative to venv?

### ISSUE THREAD

**Issue by kjcole** [paopre/Spontini#13]
I've found `pipenv` to be so much nicer than `venv`. I'm wondering if it would be possible to either 

1. offer `pipenv` as an alternative, or 
2. switch entirely to `pipenv` or 
3. offer the user an "advanced manual setup" option.

----

See:

* Official: [Pipenv documentation](https://pipenv.pypa.io/en/latest/)
* Unofficial: [Pipenv: A Guide to the New Python Packaging Tool](https://realpython.com/pipenv-guide/)

**Comment by paopre** [comment]
What would be the concrete advantage of switching to pipenv, in the Spontini's context?

**Comment by kjcole** [comment]
One more user. :wink:

Perhaps no concrete advantages directly, as with the switch from Python 2 to Python 3, the last few PyCon's I attended before the pandemic suggested that this was the direction the Python community was moving. There were an increasing number of talks about switching to TOML Pipfile in place of requirements.txt. One of the features coming in Python 11 is native TOML support... I suppose I could be "misreading the tea leaves"

It's simply a much saner, and organized, uniform way to handle all virtual environment and pips together. 

What is the advantage, directly, to Spontini using a virtual environment at all?

**Comment by paopre** [comment]
> One more user. wink
> 
> Perhaps no concrete advantages directly, as with the switch from Python 2 to Python 3, the last few PyCon's I attended before the pandemic suggested that this was the direction the Python community was moving. There were an increasing number of talks about switching to TOML Pipfile in place of requirements.txt. One of the features coming in Python 11 is native TOML support... I suppose I could be "misreading the tea leaves"
> 
> It's simply a much saner, and organized, uniform way to handle all virtual environment and pips together.
> 

AFAIK this is not generally suggested by the Python community (you can ask yourself in the #python irc channel (libera)).

> What is the advantage, directly, to Spontini using a virtual environment at all?

with the virtual environment the editor auto-installs itself, then no need to maintain a distribution of it.

**Comment by paopre** [comment]
> > One more user. wink

Hello, please check the new release (1.20-alfa). You can run Spontini-Editor by clicking on the macos executable, without having to install anythin.
