### ISSUE TITLE
Slurs and line breaks

### ISSUE THREAD

**Issue by pamposzek** [paopre/Spontini#18]
Is it possible to change shape of slurs on line break? When I use the tool on the first slur, it's properly changed, but when I change control points on the second half of the slur that's on the next line, it will also change the first one, since there are only 4 control points in the code, but it needs 8. I tried adding parentheses manually, but looks like 4 points are forced. If you move control points of the second half of the slur, it will glitch visually and there will be two slurs (one you're tweaking and untouched previous one).

Also I noticed that if you use slurs from symbols tab, Phrasing Slur Start is `-(` but should be `\(` and Phrasing Slur End is `-)` but should be `\)` (jsShape variant has it correctly).

**Comment by paopre** [comment]
> 



> Is it possible to change shape of slurs on line break? When I use the tool on the first slur, it's properly changed, but when I change control points on the second half of the slur that's on the next line, it will also change the first one, since there are only 4 control points in the code, but it needs 8. I tried adding parentheses manually, but looks like 4 points are forced. If you move control points of the second half of the slur, it will glitch visually and there will be two slurs (one you're tweaking and untouched previous one).

This  is not possible, sorry. Why would you need to break a line in a such weird way? If you need to shorten a line, see: https://github.com/paopre/Spontini/blob/master/documentation/tabular.md ("Coding rules and JSSVG/VARS blocks")

> 
> Also I noticed that if you use slurs from symbols tab, Phrasing Slur Start is `-(` but should be `\(` and Phrasing Slur End is `-)` but should be `\)` (jsShape variant has it correctly).

Thanks for reporting this. I just fixed it and pushed it to the master branch. It will be included in the next release. Meanwhile, if you need to fix it in the release you are using, just replace the "symbols.js" file (inside lib/webgui/js) 

with this one:  https://raw.githubusercontent.com/paopre/Spontini/master/lib/webgui/js/symbols.js

(this issue will be closed as soon as the new release will be published)

**Comment by pamposzek** [comment]
I don't think that's too weird, was just trying to do what you can do in Lilypond with the code:

```
Changing the shapes of the two halves of the slur makes it clearer that the slur continues over the line break:

\shape #'(
             (( 0 . 0) (0 . 0) (0 . 0) (0 . 1))
             ((0.5 . 1.5) (1 . 0) (0 . 0) (0 . -1.5))
           ) Slur
```

I was not using any of the more fancy features yet, just simply adding shape override, but I think there's a workaround.. I'll test it, but simply making a second slur after line break, and then raising starting/ending points should work. Or just use above code for rare cases like that.

Thanks for the reply and for making this awesome tool!

**Comment by paolo-pr** [comment]
> I don't think that's too weird, was just trying to do what you can do in Lilypond with the code:
> 
> ```
> Changing the shapes of the two halves of the slur makes it clearer that the slur continues over the line break:
> 
> \shape #'(
>              (( 0 . 0) (0 . 0) (0 . 0) (0 . 1))
>              ((0.5 . 1.5) (1 . 0) (0 . 0) (0 . -1.5))
>            ) Slur
> ```
> 

Can you provide a complete snippet of a testcase for what you are describing?
IIUC, you are referring to a slur which is splitted into two curves on a staff break. 
Currently only shapes with four control points are supported by the editor.
Therefore, in your case I would simply suggest to use two separate shapes, because you can easily adjust their control points with the mouse, but I need a testcase in order to help you better

**Comment by pamposzek** [comment]
> IIUC, you are referring to a slur which is splitted into two curves on a staff break.

Yes, you are exactly right, and I will use two separate shapes in such cases. I really should've figured out that earlier, simple solutions are best. Thanks for your assistance and feel free to close the issue :)

**Comment by paopre** [comment]
> > IIUC, you are referring to a slur which is splitted into two curves on a staff break.
> 
> Yes, you are exactly right, and I will use two separate shapes in such cases. I really should've figured out that earlier, simple solutions are best. Thanks for your assistance and feel free to close the issue :)

Thanks for your feedback! I'll close the issue on the next release of the editor
